# SPDX-FileCopyrightText: 2025 Will Reed
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "config"
SPDX-PackageSupplier = "Will Reed <wreed@disroot.org>"

[[annotations]]
path = "files/**"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "*.md"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
